[package]
name = "starknet_erc721"
version = "0.0.1"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=1.1.0"

[[target.starknet-contract]]